name: "Hello"

on:
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          who-to-greet: "Magnus the Lazy Cat"
          greeting: "Hello"
